project 'CarCounter.xcodeproj'

# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9'
inhibit_all_warnings!

target 'CarCounter' do
  
  use_frameworks!
	
  pod 'Masonry'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'

end
